-- ESSES SCRIPTS SÓ SERVEM PARA ANOTAÇÃO DE QUAIS SÃO OS SCRIPTS GERADOS NA CRIAÇÃO DO BANCO E DAS TABELAS.

CREATE DATABASE rede_social;

CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(175) NOT NULL,
  password VARCHAR(255) NOT NULL
);

CREATE TABLE posts (
  id SERIAL PRIMARY KEY,
  title VARCHAR(175) NOT NULL,
  description VARCHAR(300) NOT NULL,
  likes INTEGER NOT NULL DEFAULT 0,
  id_user INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE comments (
  id SERIAL PRIMARY KEY,
  comment VARCHAR(355) NOT NULL,
  id_post INTEGER NOT NULL REFERENCES posts(id) ON DELETE CASCADE
);

